Repository phaserjs/phaser, pull requests merged in 2020-04, with the labels that each got.

#5022 Docs updates
  src/gameobjects/components/Transform.js
  src/math/Vector2.js
  src/math/easing/linear/Linear.js
  src/math/easing/stepped/Stepped.js
  src/physics/arcade/PhysicsGroup.js
  src/physics/arcade/StaticPhysicsGroup.js
  src/sound/BaseSoundManager.js
  src/sound/html5/HTML5AudioSoundManager.js
  src/sound/noaudio/NoAudioSoundManager.js
  src/sound/webaudio/WebAudioSoundManager.js
Labels: 📖 Docs

#5055 Clamp audio tag volume in HTML5AudioSound
  src/sound/html5/HTML5AudioSound.js
Labels: 🍻 To be merged, 🐛 Bug

#5038 Update JSDocs for events
  plugins/spine/src/SpinePlugin.js
  src/core/Game.js
  src/gameobjects/components/Animation.js
  src/loader/LoaderPlugin.js
  src/loader/filetypes/AnimationJSONFile.js
  src/loader/filetypes/AtlasJSONFile.js
  src/loader/filetypes/AtlasXMLFile.js
  src/loader/filetypes/AudioFile.js
  src/loader/filetypes/AudioSpriteFile.js
  src/loader/filetypes/BinaryFile.js
  src/loader/filetypes/BitmapFontFile.js
  src/loader/filetypes/CSSFile.js
  src/loader/filetypes/GLSLFile.js
  src/loader/filetypes/HTMLFile.js
  src/loader/filetypes/HTMLTextureFile.js
  src/loader/filetypes/ImageFile.js
  src/loader/filetypes/JSONFile.js
  src/loader/filetypes/MultiAtlasFile.js
  src/loader/filetypes/MultiScriptFile.js
  src/loader/filetypes/PackFile.js
  src/loader/filetypes/PluginFile.js
  src/loader/filetypes/SVGFile.js
  src/loader/filetypes/SceneFile.js
  src/loader/filetypes/ScenePluginFile.js
  src/loader/filetypes/ScriptFile.js
  src/loader/filetypes/SpriteSheetFile.js
  src/loader/filetypes/TextFile.js
  src/loader/filetypes/TilemapCSVFile.js
  src/loader/filetypes/TilemapImpactFile.js
  src/loader/filetypes/TilemapJSONFile.js
  src/loader/filetypes/UnityAtlasFile.js
  src/loader/filetypes/VideoFile.js
  src/loader/filetypes/XMLFile.js
  src/physics/arcade/Body.js
  src/scene/Systems.js
Labels: 📖 Docs

#5033 Fix 'TypeError: Invalid calling object' in IE
  src/physics/matter-js/lib/core/Common.js
Labels: 🍻 To be merged, 🐛 Bug

#4995 Fix checkCollision none for tile collisions; and optimizations
  src/physics/arcade/World.js
Labels: 🐛 Bug

#5004 Fix updateText() error for headless renderer
  src/gameobjects/text/static/Text.js
Labels: 🐛 Bug (TypeScript)

#4998 Fix inputDebug shape position when the target is inside a container
  src/input/InputPlugin.js
Labels: 🍻 To be merged, 🐛 Bug

#4975 Fixed `this` return types
  src/animations/Animation.js
  src/animations/AnimationManager.js
  src/cache/BaseCache.js
  src/cameras/2d/BaseCamera.js
  src/cameras/2d/Camera.js
  src/cameras/2d/CameraManager.js
  src/cameras/controls/FixedKeyControl.js
  src/cameras/controls/SmoothedKeyControl.js
  src/curves/EllipseCurve.js
  src/curves/SplineCurve.js
  src/curves/path/Path.js
  src/data/DataManager.js
  src/geom/circle/Circle.js
  src/geom/ellipse/Ellipse.js
  src/geom/line/Line.js
  src/geom/point/Point.js
  src/geom/polygon/Polygon.js
  src/geom/rectangle/Rectangle.js
  src/geom/triangle/Triangle.js
  src/input/InputPlugin.js
  src/input/keyboard/KeyboardPlugin.js
  src/input/keyboard/keys/Key.js
  src/input/mouse/MouseManager.js
  src/input/touch/TouchManager.js
  src/plugins/PluginManager.js
Labels: 🐛 Bug (TypeScript), 📖 Docs
